apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all-logs
  namespace: cattle-logging-system
  labels:
    {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  globalOutputRefs:
    - all-logs
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: all-logs
  namespace: cattle-logging-system
  labels:
  {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  http:
    endpoint: http://{{ .Release.Name }}-log-output.{{ .Release.Namespace }}.svc/all-logs/
    buffer:
      flush_interval: 10s
      flush_mode: interval
