apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: log-generator-app
  labels:
  {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  localOutputRefs:
    - log-generator-app
  match:
    - select:
        labels:
          rancher.logging.example/app: log-generator
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: log-generator-app
  labels:
  {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  http:
    endpoint: http://{{ .Release.Name }}-log-output.{{ .Release.Namespace }}.svc/log-generator-app/
    buffer:
      flush_interval: 10s
