apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: log-generator-app
  labels:
  {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  localOutputRefs:
    - log-generator-app
  match:
    - select:
        labels:
          rancher.logging.example/app: log-generator
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: log-generator-app
  labels:
  {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  elasticsearch:
    host: elasticsearch-master.{{.Release.Namespace}}.svc
    port: 9200
    scheme: http
    index_name: log-generator-app
