apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: {{ .Release.Namespace }}-namespace
  labels:
  {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  localOutputRefs:
    - {{ .Release.Namespace }}-namespace
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ .Release.Namespace }}-namespace
  labels:
  {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  http:
    endpoint: http://{{ .Release.Name }}-log-output.{{ .Release.Namespace }}.svc/{{ .Release.Namespace }}-namespace/
    buffer:
      flush_interval: 10s
