apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: {{ .Release.Namespace }}-namespace
  labels:
  {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  localOutputRefs:
    - {{ .Release.Namespace }}-namespace
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: {{ .Release.Namespace }}-namespace
  labels:
  {{- include "rancher-logging-example.labels" . | nindent 4 }}
spec:
  elasticsearch:
    host: elasticsearch-master.{{.Release.Namespace}}.svc
    port: 9200
    scheme: http
    index_name: {{ .Release.Namespace }}-namespace
