# Default values for rancher-logging-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
log-generator:
  replicaCount: 2
  resources:
    limits:
      memory: 16Mi
    requests:
      memory: 4Mi
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: cattle.io/os
      operator: "Equal"
      value: "linux"
      effect: NoSchedule
log-output:
  replicaCount: 1
  resources:
    limits:
      memory: 16Mi
    requests:
      memory: 8Mi
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: cattle.io/os
      operator: "Equal"
      value: "linux"
      effect: NoSchedule
